# Generated by Django 3.0 on 2019-12-03 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('cancelled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Gigfinder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('api_url', models.URLField()),
                ('api_key', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Musicbrainz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mbid', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Organity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hlwtadmin.Address')),
            ],
        ),
        migrations.CreateModel(
            name='OrganityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RelationOrganityOrganity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('relation_type', models.CharField(max_length=200)),
                ('entity_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organitya', to='hlwtadmin.Organity')),
                ('entity_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organityb', to='hlwtadmin.Organity')),
            ],
        ),
        migrations.CreateModel(
            name='RelationConcertOrganity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organity_credited_as', models.CharField(max_length=200)),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hlwtadmin.Concert')),
                ('organity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hlwtadmin.Organity')),
            ],
        ),
        migrations.CreateModel(
            name='RelationConcertMusicbrainz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hlwtadmin.Concert')),
                ('musicbrainz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hlwtadmin.Musicbrainz')),
            ],
        ),
        migrations.CreateModel(
            name='RawVenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_venue', models.CharField(max_length=200)),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hlwtadmin.Organity')),
            ],
        ),
        migrations.AddField(
            model_name='organity',
            name='organity_type',
            field=models.ManyToManyField(to='hlwtadmin.OrganityType'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hlwtadmin.Country')),
            ],
        ),
        migrations.CreateModel(
            name='GigfinderUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('gigfinder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hlwtadmin.Gigfinder')),
                ('musicbrainz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hlwtadmin.Musicbrainz')),
            ],
        ),
        migrations.CreateModel(
            name='ConcertAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('gigfinder_artist_name', models.CharField(max_length=200)),
                ('gigfinder_concert_id', models.CharField(max_length=200)),
                ('last_seen_on', models.DateField(auto_now=True)),
                ('concert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hlwtadmin.Concert')),
                ('gigfinder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hlwtadmin.Gigfinder')),
                ('musicbrainz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hlwtadmin.Musicbrainz')),
                ('raw_venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hlwtadmin.RawVenue')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hlwtadmin.Location'),
        ),
    ]
