# Generated by Django 3.0 on 2020-01-24 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('disambiguation', models.CharField(blank=True, max_length=200, null=True)),
                ('mbid', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('include', models.BooleanField(default=False)),
                ('exclude', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('cancelled', models.BooleanField(blank=True, default=False, null=True)),
                ('verified', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GigFinder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('base_url', models.URLField()),
                ('api_key', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hlwtadmin.Country')),
            ],
            options={
                'ordering': ['country', 'city'],
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('disambiguation', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hlwtadmin.Location')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganisationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RelationConcertOrganisationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_venue', models.CharField(max_length=200)),
                ('raw_location', models.CharField(blank=True, max_length=200, null=True)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hlwtadmin.Organisation')),
            ],
            options={
                'ordering': ['raw_venue'],
            },
        ),
        migrations.CreateModel(
            name='RelationOrganisationOrganisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('relation_type', models.CharField(max_length=200)),
                ('organisation_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organisationa', to='hlwtadmin.Organisation')),
                ('organisation_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organisationb', to='hlwtadmin.Organisation')),
            ],
        ),
        migrations.CreateModel(
            name='RelationConcertOrganisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_credited_as', models.CharField(blank=True, max_length=200, null=True)),
                ('unverified', models.BooleanField(blank=True, default=False)),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hlwtadmin.Concert')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hlwtadmin.Organisation')),
                ('relation_type', models.ManyToManyField(blank=True, to='hlwtadmin.RelationConcertOrganisationType')),
            ],
        ),
        migrations.CreateModel(
            name='RelationConcertArtist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_credited_as', models.CharField(blank=True, max_length=200, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hlwtadmin.Artist')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hlwtadmin.Concert')),
            ],
        ),
        migrations.CreateModel(
            name='RelationArtistArtist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('relation_type', models.CharField(max_length=200)),
                ('artist_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artista', to='hlwtadmin.Artist')),
                ('artist_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artistb', to='hlwtadmin.Artist')),
            ],
        ),
        migrations.AddField(
            model_name='organisation',
            name='organisation_type',
            field=models.ManyToManyField(blank=True, to='hlwtadmin.OrganisationType'),
        ),
        migrations.CreateModel(
            name='GigFinderUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hlwtadmin.Artist')),
                ('gigfinder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hlwtadmin.GigFinder')),
            ],
        ),
        migrations.CreateModel(
            name='ConcertAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('gigfinder_concert_id', models.URLField()),
                ('last_seen_on', models.DateField(auto_now=True)),
                ('ignore', models.BooleanField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hlwtadmin.Artist')),
                ('concert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hlwtadmin.Concert')),
                ('gigfinder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hlwtadmin.GigFinder')),
                ('raw_venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hlwtadmin.Venue')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
