# Generated by Django 3.0 on 2020-02-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlwtadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concertannouncement',
            options={'ordering': ['last_seen_on', '-date']},
        ),
        migrations.AlterField(
            model_name='artist',
            name='mbid',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
