# Generated by Django 3.0 on 2019-12-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlwtadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gigfinder',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='gigfinder',
            name='api_url',
        ),
        migrations.AddField(
            model_name='concertannouncement',
            name='ignore',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
