# Generated by Django 3.0 on 2019-12-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlwtadmin', '0002_auto_20191203_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationConcertOrganityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='relationconcertorganity',
            name='relation_type',
            field=models.ManyToManyField(to='hlwtadmin.RelationConcertOrganityType'),
        ),
    ]
