# Generated by Django 3.0 on 2019-12-06 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hlwtadmin', '0003_auto_20191204_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['address', 'location']},
        ),
        migrations.AlterModelOptions(
            name='concert',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='concertannouncement',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='musicbrainz',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='organity',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='rawvenue',
            options={'ordering': ['raw_venue']},
        ),
    ]
