# Generated by Django 3.0 on 2020-02-05 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hlwtadmin', '0004_organisationsmerge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcertsMerge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_objects', models.ManyToManyField(related_name='aliases', to='hlwtadmin.Concert')),
                ('primary_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary', to='hlwtadmin.Concert')),
            ],
        ),
    ]
