# Generated by Django 3.0 on 2020-02-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlwtadmin', '0005_concertsmerge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationconcertartist',
            options={'ordering': ['concert']},
        ),
        migrations.AlterModelOptions(
            name='relationconcertorganisation',
            options={'ordering': ['concert']},
        ),
        migrations.AddField(
            model_name='concert',
            name='ignore',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalconcert',
            name='ignore',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalorganisation',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='concertannouncement',
            name='gigfinder_concert_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
