# Generated by Django 3.0 on 2020-02-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlwtadmin', '0007_auto_20200206_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='non_assignable',
            field=models.BooleanField(default=False),
        ),
    ]
