# Generated by Django 3.0 on 2020-02-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlwtadmin', '0008_venue_non_assignable'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganisation',
            name='unverified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='unverified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
