# Generated by Django 3.0 on 2020-02-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlwtadmin', '0009_auto_20200207_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.ManyToManyField(blank=True, to='hlwtadmin.Genre'),
        ),
        migrations.AddField(
            model_name='concert',
            name='genre',
            field=models.ManyToManyField(blank=True, to='hlwtadmin.Genre'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='genre',
            field=models.ManyToManyField(blank=True, to='hlwtadmin.Genre'),
        ),
    ]
