# Generated by Django 3.0 on 2020-02-07 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hlwtadmin', '0010_auto_20200207_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationConcertConcert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(max_length=200)),
                ('concert_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concerta', to='hlwtadmin.Concert')),
                ('concert_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concertb', to='hlwtadmin.Concert')),
            ],
        ),
    ]
