# Generated by Django 3.0 on 2020-02-07 14:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hlwtadmin', '0011_relationconcertconcert'),
    ]

    operations = [
        migrations.AddField(
            model_name='concertannouncement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concertannouncement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
