# Generated by Django 3.0 on 2020-02-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlwtadmin', '0012_auto_20200207_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationArtistArtistType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RelationConcertArtistType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RelationConcertConcertType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RelationOrganisationOrganisationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='historicalrelationconcertorganisation',
            old_name='unverified',
            new_name='verified',
        ),
        migrations.RenameField(
            model_name='relationconcertorganisation',
            old_name='unverified',
            new_name='verified',
        ),
        migrations.RemoveField(
            model_name='historicalorganisation',
            name='unverified',
        ),
        migrations.RemoveField(
            model_name='historicalrelationartistartist',
            name='relation_type',
        ),
        migrations.RemoveField(
            model_name='historicalrelationorganisationorganisation',
            name='relation_type',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='unverified',
        ),
        migrations.AddField(
            model_name='concert',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concert',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concertannouncement',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concertannouncement',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalconcert',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalconcert',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalorganisation',
            name='verified',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='verified',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.RemoveField(
            model_name='relationartistartist',
            name='relation_type',
        ),
        migrations.RemoveField(
            model_name='relationconcertconcert',
            name='relation_type',
        ),
        migrations.RemoveField(
            model_name='relationorganisationorganisation',
            name='relation_type',
        ),
        migrations.AddField(
            model_name='relationconcertartist',
            name='relation_type',
            field=models.ManyToManyField(blank=True, to='hlwtadmin.RelationConcertArtistType'),
        ),
        migrations.AddField(
            model_name='relationartistartist',
            name='relation_type',
            field=models.ManyToManyField(blank=True, to='hlwtadmin.RelationArtistArtistType'),
        ),
        migrations.AddField(
            model_name='relationconcertconcert',
            name='relation_type',
            field=models.ManyToManyField(blank=True, to='hlwtadmin.RelationConcertConcertType'),
        ),
        migrations.AddField(
            model_name='relationorganisationorganisation',
            name='relation_type',
            field=models.ManyToManyField(blank=True, to='hlwtadmin.RelationOrganisationOrganisationType'),
        ),
    ]
