# Generated by Django 3.0 on 2020-02-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlwtadmin', '0016_auto_20200225_1006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concertannouncement',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='location',
            name='subcountry',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
