# Generated by Django 3.0 on 2020-02-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlwtadmin', '0017_auto_20200228_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='verified',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
