# Generated by Django 3.0 on 2020-03-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlwtadmin', '0019_locationsmerge'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganisation',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
