# Generated by Django 3.0 on 2020-03-20 11:11

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('hlwtadmin', '0021_location_zipcode'),
    ]

    operations = [
        UnaccentExtension()
    ]
