# Generated by Django 3.0 on 2020-03-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlwtadmin', '0022_auto_20200320_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='annotation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalconcert',
            name='annotation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
