# Generated by Django 3.0 on 2020-04-15 14:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hlwtadmin', '0025_auto_20200414_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gigfinderurl',
            options={'ordering': ['-last_confirmed_by_musicbrainz', '-last_synchronized']},
        ),
        migrations.AddField(
            model_name='historicalorganisation',
            name='end_date_precision',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Precise up to the year'), (5, 'Precise up to the month'), (8, 'Precise up to the day')], default=2),
        ),
        migrations.AddField(
            model_name='historicalorganisation',
            name='start_date_precision',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Precise up to the year'), (5, 'Precise up to the month'), (8, 'Precise up to the day')], default=2),
        ),
        migrations.AddField(
            model_name='historicalrelationartistartist',
            name='end_date_precision',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Precise up to the year'), (5, 'Precise up to the month'), (8, 'Precise up to the day')], default=2),
        ),
        migrations.AddField(
            model_name='historicalrelationartistartist',
            name='start_date_precision',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Precise up to the year'), (5, 'Precise up to the month'), (8, 'Precise up to the day')], default=2),
        ),
        migrations.AddField(
            model_name='historicalrelationorganisationorganisation',
            name='end_date_precision',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Precise up to the year'), (5, 'Precise up to the month'), (8, 'Precise up to the day')], default=2),
        ),
        migrations.AddField(
            model_name='historicalrelationorganisationorganisation',
            name='start_date_precision',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Precise up to the year'), (5, 'Precise up to the month'), (8, 'Precise up to the day')], default=2),
        ),
        migrations.AddField(
            model_name='organisation',
            name='end_date_precision',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Precise up to the year'), (5, 'Precise up to the month'), (8, 'Precise up to the day')], default=2),
        ),
        migrations.AddField(
            model_name='organisation',
            name='start_date_precision',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Precise up to the year'), (5, 'Precise up to the month'), (8, 'Precise up to the day')], default=2),
        ),
        migrations.AddField(
            model_name='relationartistartist',
            name='end_date_precision',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Precise up to the year'), (5, 'Precise up to the month'), (8, 'Precise up to the day')], default=2),
        ),
        migrations.AddField(
            model_name='relationartistartist',
            name='start_date_precision',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Precise up to the year'), (5, 'Precise up to the month'), (8, 'Precise up to the day')], default=2),
        ),
        migrations.AddField(
            model_name='relationorganisationorganisation',
            name='end_date_precision',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Precise up to the year'), (5, 'Precise up to the month'), (8, 'Precise up to the day')], default=2),
        ),
        migrations.AddField(
            model_name='relationorganisationorganisation',
            name='start_date_precision',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Precise up to the year'), (5, 'Precise up to the month'), (8, 'Precise up to the day')], default=2),
        ),
        migrations.AlterField(
            model_name='gigfinderurl',
            name='last_synchronized',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc)),
        ),
    ]
