# Generated by Django 3.0 on 2020-05-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlwtadmin', '0026_auto_20200415_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='concertannouncement',
            name='is_festival',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='concertannouncement',
            name='until_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
