# Generated by Django 3.0 on 2020-05-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlwtadmin', '0027_auto_20200519_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='until_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='historicalconcert',
            name='until_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
