# Generated by Django 3.0 on 2020-05-22 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hlwtadmin', '0029_auto_20200522_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalidentifier',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hlwtadmin.ExternalIdentifierService'),
        ),
    ]
