# Generated by Django 3.0 on 2020-05-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlwtadmin', '0030_auto_20200522_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganisation',
            name='sort_name',
            field=models.CharField(default='No sort name provided', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisation',
            name='sort_name',
            field=models.CharField(default='No sort name provided', max_length=200),
            preserve_default=False,
        ),
    ]
