# Generated by Django 3.0 on 2020-06-15 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hlwtadmin', '0032_auto_20200529_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorganisation',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalorganisation',
            name='location',
        ),
        migrations.RemoveField(
            model_name='historicalrelationartistartist',
            name='artist_a',
        ),
        migrations.RemoveField(
            model_name='historicalrelationartistartist',
            name='artist_b',
        ),
        migrations.RemoveField(
            model_name='historicalrelationartistartist',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalrelationconcertartist',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='historicalrelationconcertartist',
            name='concert',
        ),
        migrations.RemoveField(
            model_name='historicalrelationconcertartist',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalrelationconcertorganisation',
            name='concert',
        ),
        migrations.RemoveField(
            model_name='historicalrelationconcertorganisation',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalrelationconcertorganisation',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='historicalrelationorganisationorganisation',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalrelationorganisationorganisation',
            name='organisation_a',
        ),
        migrations.RemoveField(
            model_name='historicalrelationorganisationorganisation',
            name='organisation_b',
        ),
        migrations.DeleteModel(
            name='HistoricalConcert',
        ),
        migrations.DeleteModel(
            name='HistoricalOrganisation',
        ),
        migrations.DeleteModel(
            name='HistoricalRelationArtistArtist',
        ),
        migrations.DeleteModel(
            name='HistoricalRelationConcertArtist',
        ),
        migrations.DeleteModel(
            name='HistoricalRelationConcertOrganisation',
        ),
        migrations.DeleteModel(
            name='HistoricalRelationOrganisationOrganisation',
        ),
    ]
