# Generated by Django 3.0 on 2020-07-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlwtadmin', '0033_auto_20200615_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concertsmerge',
            options={'ordering': ['primary_object']},
        ),
        migrations.AddField(
            model_name='concert',
            name='manual',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
