# Generated by Django 3.0 on 2020-07-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlwtadmin', '0034_auto_20200722_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='disambiguation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
