# Generated by Django 3.0 on 2020-09-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlwtadmin', '0035_location_disambiguation'),
    ]

    operations = [
        migrations.AddField(
            model_name='concertannouncement',
            name='cancelled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
