# Generated by Django 3.0.7 on 2020-11-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlwtadmin', '0037_historicalconcert_historicalconcertannouncement_historicalcountry_historicalexternalidentifier_histo'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='artist',
            field=models.ManyToManyField(blank=True, default=None, to='hlwtadmin.Artist'),
        ),
        migrations.AddField(
            model_name='concert',
            name='organisation',
            field=models.ManyToManyField(blank=True, default=None, to='hlwtadmin.Organisation'),
        ),
    ]
