# Generated by Django 3.0.7 on 2020-12-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlwtadmin', '0040_auto_20201130_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='historicalconcert',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
