# Generated by Django 3.0.7 on 2020-12-03 11:16

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hlwtadmin', '0041_auto_20201202_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='evidence',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='concert',
            name='program',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='historicalconcert',
            name='evidence',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='historicalconcert',
            name='program',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='historicalrelationconcertartist',
            name='roles',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('main_artist', 'Main artist'), ('ensemble', 'Ensemble'), ('conductor', 'Conductor'), ('solist', 'Solist'), ('composer', 'Composer'), ('not specified', 'not specified')], max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='relationconcertartist',
            name='roles',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('main_artist', 'Main artist'), ('ensemble', 'Ensemble'), ('conductor', 'Conductor'), ('solist', 'Solist'), ('composer', 'Composer'), ('not specified', 'not specified')], max_length=60, null=True),
        ),
    ]
