# Generated by Django 3.0.7 on 2021-01-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlwtadmin', '0042_auto_20201203_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalconcert',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
