# Generated by Django 3.0.7 on 2021-01-26 09:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlwtadmin', '0043_auto_20210126_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigfinderurl',
            name='ignore_periods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), blank=True, null=True, size=2),
        ),
    ]
