# Generated by Django 3.0 on 2021-02-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlwtadmin', '0044_gigfinderurl_ignore_periods'),
    ]

    operations = [
        migrations.AddField(
            model_name='concertannouncement',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='historicalconcertannouncement',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
