# Generated by Django 3.0.7 on 2021-02-24 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hlwtadmin', '0045_auto_20210223_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gigfinderurl',
            old_name='ignore_end',
            new_name='active_end',
        ),
        migrations.RenameField(
            model_name='gigfinderurl',
            old_name='ignore_start',
            new_name='active_start',
        ),
    ]
