# Generated by Django 3.0.7 on 2021-03-04 11:10

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('hlwtadmin', '0046_auto_20210224_1052'),
        ('hlwtadmin', '0045_auto_20210219_1714'),
    ]

    operations = [
    ]
