# Generated by Django 3.0 on 2021-07-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlwtadmin', '0047_merge_20210304_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='begin',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='end',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganisation',
            name='sort_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='sort_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
